plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'it.gael'
version '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    // Comunicazione ZMQ (fondamentale per il Brain)
    implementation 'org.zeromq:jeromq:0.5.3'
    
    // JSON e Logging
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.slf4j:slf4j-simple:2.0.7'

    // Compila contro i jar presenti nella cartella libs (Hytale Server)
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

shadowJar {
    // Il jar 'grasso' avrà il suffisso -all
    archiveClassifier.set('all')
    mergeServiceFiles()
}
